{'name': 'Wuchang Property Local Cloud',
 'version': '18.0.1.0.0',
 'category': 'Property Management',
 'summary': '會員主權型 1+2/3/4 分散式算力設備介面',
 'description': '\n五常智慧雲物業管理系統：\n會員權限來源設備 × 商家/管委會場域驗證設備 × 受託營運治理設備 × 團體客戶端在地雲端商設備。\n',
 'author': 'CHIANG CHENG LUNG / Wuchang Community Development Association',
 'depends': ['base'],
 'data': ['security/ir.model.access.csv',
          'views/wuchang_property_views.xml',
          'views/wuchang_pos_policy_views.xml',
          'views/wuchang_franchise_relationship_views.xml',
          'views/wuchang_ticket_opening_views.xml',
          'views/wuchang_ticket_quota_buckets_views.xml',
          'views/wuchang_google_nonprofit_resource_views.xml',
          'views/wuchang_company_association_registration_views.xml',
          'views/wuchang_company_google_workspace_views.xml'],
 'installable': True,
 'application': True,
 'license': 'LGPL-3'}
