[options]
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo

admin_passwd = $pbkdf2-sha512$600000$QKi1ljIGoDQmZCxlrFVqzQ$MpTOfResNwcgVHbr28n.JX3bHuX7Q/XrbWnuO7D3Y8Wb6v9/xMJyaIPyaWZwmGDfKhLCmWCBIrQvwB.DRTVqYw

db_host = wuchang_os_pg
db_port = 5432
db_user = odoo
db_name = wuchang_odoo
dbfilter = ^wuchang_odoo$

list_db = False

xmlrpc = True
xmlrpc_interface = 0.0.0.0
xmlrpc_port = 8069

proxy_mode = True
workers = 0
max_cron_threads = 2

log_level = info

server_wide_modules = base,web,pm3_runtime_sync
