{
    "name": "WuChang Cafe AI Gateway",
    "version": "18.0.2.3.1",
    "category": "Point of Sale",
    "summary": "上品聊國咖啡館重新總店：小J影音店員、自然語言點餐與 8DADI 數位設備社區團結行動。",
    "author": "WuChang / Liaoguo Cafe",
    "license": "LGPL-3",
    "depends": [
        "base",
        "web",
        "portal",
        "auth_oauth",
        "point_of_sale",
        "pos_restaurant",
        "pos_self_order",
        "product",
    ],
    "data": [
        "data/wuchang_portal_template.xml",
        "security/wuchang_cafe_merchant_security.xml",
        "security/ir.model.access.csv",
        "views/wuchang_cafe_ai_eventbook_views.xml",
        "views/wuchang_cafe_gateway_views.xml",
        "views/wuchang_cafe_merchant_account_views.xml",
        "views/wuchang_ai_compute_binding_views.xml",
        "views/wuchang_xiaoj_portal_templates.xml",
    ],
    "installable": True,
    "application": False,
}
