services:
  d1:
    image: w7tp-indexer:formal-v1-2a963ec0cfd2
    pull_policy: never
  d2:
    image: w7tp-indexer:formal-v1-2a963ec0cfd2
    pull_policy: never
  d3:
    image: w7tp-indexer:formal-v1-2a963ec0cfd2
    pull_policy: never
  d4:
    image: w7tp-indexer:formal-v1-2a963ec0cfd2
    pull_policy: never
  d5:
    image: w7tp-indexer:formal-v1-2a963ec0cfd2
    pull_policy: never
  d6:
    image: w7tp-indexer:formal-v1-2a963ec0cfd2
    pull_policy: never
  d7:
    image: w7tp-indexer:formal-v1-2a963ec0cfd2
    pull_policy: never
  d8:
    image: w7tp-indexer:formal-v1-2a963ec0cfd2
    pull_policy: never
  total-field-core:
    image: w7tp-indexer:formal-v1-2a963ec0cfd2
    pull_policy: never
