import * as THREE from './node_modules/three/build/three.module.js';
import { GLTFLoader } from './node_modules/three/examples/jsm/loaders/GLTFLoader.js';
import { OrbitControls } from './node_modules/three/examples/jsm/controls/OrbitControls.js';

const canvas = document.querySelector('#viewport'), load = document.querySelector('#load'), status = document.querySelector('#status');
const renderer = new THREE.WebGLRenderer({canvas, antialias:true, alpha:true}); renderer.setPixelRatio(Math.min(devicePixelRatio,2)); renderer.outputColorSpace=THREE.SRGBColorSpace;
const scene=new THREE.Scene(); scene.fog=new THREE.Fog(0x081016,8,24);
const camera=new THREE.PerspectiveCamera(38,1,.1,100); camera.position.set(0,1.4,5);
const controls=new OrbitControls(camera,canvas); controls.enableDamping=true; controls.target.set(0,1,0);
scene.add(new THREE.HemisphereLight(0xa8e9ff,0x0b1015,2.1)); const key=new THREE.DirectionalLight(0xfff0df,2.6); key.position.set(3,5,4); scene.add(key);
const floor=new THREE.Mesh(new THREE.CircleGeometry(7,64),new THREE.MeshStandardMaterial({color:0x12303b,roughness:.8,metalness:.08})); floor.rotation.x=-Math.PI/2; scene.add(floor);
const state={action:'站立', emotion:'喜-1', phoneme:'休止', adi:{}, bones:null, face:null, model:null, materialLum:1};
const actionDefs=['坐下','起立','步行','慢跑','跳躍']; const emotionDefs=['喜-1','喜-2','喜-3','怒-1','怒-2','怒-3','哀-1','哀-2','哀-3','樂-1','樂-2','樂-3']; const phonemeDefs=['休止','A','E','I','O','U','M'];
function buttons(id,items,cb){const box=document.querySelector(id);items.forEach(x=>{const b=document.createElement('button');b.textContent=x;b.onclick=()=>{cb(x);box.querySelectorAll('button').forEach(n=>n.classList.toggle('active',n===b));};box.append(b);});box.firstChild.classList.add('active');}
buttons('#actions',actionDefs,x=>state.action=x); buttons('#emotions',emotionDefs,x=>{state.emotion=x;drawFace();}); buttons('#phonemes',phonemeDefs,x=>{state.phoneme=x;drawFace();});
const adi=await fetch('./adi_mapping.json').then(r=>r.json()); adi.coordinates.forEach(c=>{state.adi[c.id]=c.default;const row=document.createElement('label');row.className='adi-row';row.innerHTML=`<span>${c.label}</span><input aria-label="${c.label}" type="range" min="0" max="1" step="0.01" value="${c.default}"><output>${c.default.toFixed(2)}</output>`;const input=row.querySelector('input'),out=row.querySelector('output');input.oninput=()=>{state.adi[c.id]=+input.value;out.value=input.value;out.textContent=(+input.value).toFixed(2);};document.querySelector('#adi').append(row);});
function makeFace(){const c=document.createElement('canvas');c.width=512;c.height=512;const texture=new THREE.CanvasTexture(c);texture.colorSpace=THREE.SRGBColorSpace;const mesh=new THREE.Mesh(new THREE.PlaneGeometry(1,1),new THREE.MeshBasicMaterial({map:texture,transparent:true,depthWrite:false}));mesh.userData.canvas=c;mesh.userData.texture=texture;return mesh;}
function drawFace(){if(!state.face)return;const c=state.face.userData.canvas,g=c.getContext('2d'),[mood,levelS]=state.emotion.split('-'),level=+levelS;g.clearRect(0,0,512,512);const ink=mood==='怒'?'#c64d4d':mood==='哀'?'#75a6da':'#173942';g.strokeStyle=ink;g.fillStyle=ink;g.lineWidth=20;g.lineCap='round'; const eyeY=190, eye=level*7;
if(mood==='怒'){g.beginPath();g.moveTo(112,eyeY-eye);g.lineTo(195,eyeY+eye);g.moveTo(317,eyeY+eye);g.lineTo(400,eyeY-eye);g.stroke();}else if(mood==='哀'){g.beginPath();g.arc(155,eyeY,30,Math.PI,0);g.arc(357,eyeY,30,Math.PI,0);g.stroke();}else{g.beginPath();g.arc(155,eyeY,26,0,Math.PI*2);g.arc(357,eyeY,26,0,Math.PI*2);g.fill();}
const mouth={休止:[210,300,92,10],A:[185,270,142,92],E:[175,300,160,30],I:[230,265,52,104],O:[205,270,102,95],U:[210,295,92,55],M:[180,302,150,12]}[state.phoneme];g.beginPath();if(state.phoneme==='休止'||state.phoneme==='M'){g.roundRect(mouth[0],mouth[1],mouth[2],mouth[3],10);g.fill();}else{g.ellipse(mouth[0]+mouth[2]/2,mouth[1]+mouth[3]/2,mouth[2]/2,mouth[3]/2,0,0,Math.PI*2);g.fill();}if(mood==='樂'||mood==='喜'){g.strokeStyle='#d4f7ed';g.lineWidth=7;g.beginPath();g.arc(256,310,82,0,Math.PI);g.stroke();}state.face.userData.texture.needsUpdate=true;}
function rigModel(model){const box=new THREE.Box3().setFromObject(model), size=box.getSize(new THREE.Vector3()), center=box.getCenter(new THREE.Vector3()), min=box.min, max=box.max; const root=new THREE.Bone();root.name='Root';root.position.set(center.x,min.y,center.z);root.userData.baseY=root.position.y;const spine=new THREE.Bone();spine.name='Spine';spine.position.set(0,size.y*.36,0);const head=new THREE.Bone();head.name='Head';head.position.set(0,size.y*.34,0);const la=new THREE.Bone();la.name='Arm.L';la.position.set(-size.x*.25,size.y*.15,0);const ra=new THREE.Bone();ra.name='Arm.R';ra.position.set(size.x*.25,size.y*.15,0);const ll=new THREE.Bone();ll.name='Leg.L';ll.position.set(-size.x*.16,-size.y*.36,0);const rl=new THREE.Bone();rl.name='Leg.R';rl.position.set(size.x*.16,-size.y*.36,0);root.add(spine);spine.add(head,la,ra,ll,rl);model.add(root);const bones=[root,spine,head,la,ra,ll,rl], skeleton=new THREE.Skeleton(bones);
 model.traverse(obj=>{if(!obj.isMesh)return;const geo=obj.geometry.clone(), pos=geo.attributes.position;const si=new Uint16Array(pos.count*4),sw=new Float32Array(pos.count*4);for(let i=0;i<pos.count;i++){const v=new THREE.Vector3().fromBufferAttribute(pos,i).applyMatrix4(obj.matrixWorld);const y=(v.y-min.y)/Math.max(size.y,.001), x=(v.x-center.x)/Math.max(size.x,.001);let bone=1;if(y>.73)bone=2;else if(y>.28&&Math.abs(x)>.22)bone=x<0?3:4;else if(y<.3&&Math.abs(x)>.08)bone=x<0?5:6;si[i*4]=bone;sw[i*4]=1;}geo.setAttribute('skinIndex',new THREE.Uint16BufferAttribute(si,4));geo.setAttribute('skinWeight',new THREE.Float32BufferAttribute(sw,4));const skin=new THREE.SkinnedMesh(geo,obj.material);skin.name=`${obj.name||'mesh'}__runtime_skinned`;skin.position.copy(obj.position);skin.quaternion.copy(obj.quaternion);skin.scale.copy(obj.scale);skin.castShadow=skin.receiveShadow=true;obj.parent.add(skin);obj.parent.remove(obj);skin.bind(skeleton);});
 const face=makeFace();face.scale.set(size.x*.42,size.x*.42,1);face.position.set(center.x,center.y+size.y*.14,max.z+size.z*.025);model.add(face);state.bones={root,spine,head,la,ra,ll,rl};state.face=face;drawFace(); const radius=Math.max(size.x,size.y)*.78;camera.position.set(center.x,center.y+size.y*.05,max.z+radius*3);controls.target.set(center.x,center.y,center.z);controls.update();}
function animate(t){requestAnimationFrame(animate);if(state.bones){const b=state.bones,s=t*.001,cad=.6+state.adi.time*1.4,gain=.35+state.adi.authority*.9,restraint=1-state.adi.risk*.65,w=s*cad;[b.la,b.ra,b.ll,b.rl].forEach(x=>x.rotation.set(0,0,0));b.root.position.y=b.root.userData.baseY;b.spine.rotation.x=0;b.head.rotation.y=Math.sin(s*.7)*.08*state.adi.relation;
 if(state.action==='坐下'){b.spine.rotation.x=.32; b.ll.rotation.x=-1.25;b.rl.rotation.x=-1.25;b.root.position.y=b.root.userData.baseY-.14;} else if(state.action==='起立'){b.spine.rotation.x=.32*(1-(Math.sin(s*2)+1)/2);b.root.position.y=b.root.userData.baseY-.14*(1-(Math.sin(s*2)+1)/2);} else if(state.action==='步行'||state.action==='慢跑'){const k=state.action==='慢跑'?1.7:1, a=Math.sin(w*k)*.62*gain*restraint;b.ll.rotation.x=a;b.rl.rotation.x=-a;b.la.rotation.x=-a*.65;b.ra.rotation.x=a*.65;b.root.position.y=b.root.userData.baseY+Math.abs(Math.sin(w*k))*-.035*k;} else if(state.action==='跳躍'){const phase=(Math.sin(w*1.6)+1)/2;b.root.position.y=b.root.userData.baseY+phase*.42;b.ll.rotation.x=-.45*(1-phase);b.rl.rotation.x=-.45*(1-phase);b.la.rotation.z=.28*(1-phase);b.ra.rotation.z=-.28*(1-phase);} const lum=.55+state.adi.resource*.8;scene.traverse(x=>{if(x.isMesh&&x.material&&'emissiveIntensity'in x.material)x.material.emissiveIntensity=.08*lum;});}
 controls.update();renderer.render(scene,camera);}
function resize(){const r=canvas.getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix();}new ResizeObserver(resize).observe(canvas);resize();
new GLTFLoader().load('./assets/xiaoj_single_core_geometry.glb',gltf=>{const model=gltf.scene;scene.add(model);rigModel(model);load.remove();status.textContent='已載入：PBR 材質、7 骨節蒙皮、12 組三級情緒、7 組發音與 5 組動作。';animate(0);},undefined,error=>{load.textContent='模型載入失敗';status.textContent=String(error);});
