tunnel: wuchang-smart-cloud
credentials-file: /home/taiji_admin/.cloudflared/wuchang-smart-cloud.json

ingress:
  - hostname: wuchang.life
    service: http://127.0.0.1:8089

  - hostname: www.wuchang.life
    service: http://127.0.0.1:8089

  - service: http_status:404
